---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataprocessingservice
spec:
  selector:
    matchLabels:
      app: dataprocessingservice
  replicas: 1
  template:
    metadata:
      labels:
        app: dataprocessingservice
    spec:
      containers:
      - name: dataprocessingservice
        image: dataprocessingservice
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dataprocessingservice
  labels:
    app: dataprocessingservice
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: dataprocessingservice
